= Making changes to bootc systems

In this lab, you will learn how to make configuration or software changes in images and apply them to bootc hosts. 

[#update-container]
== Changing the bootc image

We've created our first system but there are a few things that might be missing we typically 
do to our systems. Not requiring a password every time we use sudo might be something we allow 
admins to do. We may also need to put notices on logins or present info in the MOTD. Let's make 
some changes to how the system behaves. 


RHEL supports drop-in directories for several services and applications, including 
`sudo` privileges. 

Drop-in support lets us add a file to a `<servicename>.d` directory rather than editing 
the main configuration file. You might already be familiar with drop-in config files from working with Apache and it's `/etc/httpd/conf.d/` directory. Using drop-in files lets us affect the configuration of a system, without needing to edit a file in place, or carry a full configuration file in the image.


Let's address the sudoers password first, by allowing users in the wheel group to not need to enter their password.

[source,bash,role="execute",subs=attributes+]
----
nano 10-wheel
----

Add the following and save the file

[source,text,role="execute",subs=attributes+]
----
# Enable passwordless sudo for the wheel group
%wheel        ALL=(ALL)       NOPASSWD: ALL
----

And let's provide a message of the day!

[source,bash,role="execute",subs=attributes+]
----
nano console_kargs.conf
----

Add the following and save the file

[source,text,role="execute",subs=attributes+]
----
kargs = ["console=tty0", "console=ttyS0,115200n8"]
----

Now that we have our new configs, we can add them to the Containerfile and rebuild the image.

[source,dockerfile,role="execute",subs=attributes+]
----

# Add image controlled configs
COPY 10-wheel /etc/sudoers.d/wheel
COPY console_kargs.conf /usr/lib/bootc/kargs.d/05-cloud-kargs.toml
# RUN echo "d /var/lib/rsyslog     700 root root -" >> /etc/tmpfiles.d/rsyslog.conf
----


[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----

And make sure to push it to the registry:

[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

[#distribute]
== Distributing the bootc image

Now that we have a full operating system in a standard OCI container image, we can use
standard container registries to host and distribute our OS images. The only atypical thing so far 
is what's in the base image. How we added software or files to the image is the same as any other 
application container. The special sauce of `bootc` comes when a host is running.

We have a registry available within the lab environment we can push our image to:

[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

Authenticate and add to Containerfile

[source,bash,role="execute",subs=attributes+]
----
podman login -u core -p redhat registry-GUID.DOMAIN
----

[source,bash,role="execute",subs=attributes+]
----
podman login -u core -p redhat registry-GUID.DOMAIN --authfile=auth.json
----

[source,dockerfile,role="execute",subs=attributes+]
----
COPY auth.json /etc/ostree/auth.json
----
[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----

[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

We now have replaced the original image in the registry we used to create the virtual machine with a new image. This is the standard workflow for making changes to an image mode host. All of our updates, additions, or changes are done via the build systems we use, and are then published to be used by the hosts. We'll talk more about updates and how to differentiate them in a later exercise.

[#update-vm]
== Updating the virtual machine

[source,bash,role="execute",subs=attributes+]
----
podman login -u core -p redhat registry-GUID.DOMAIN --authfile=auth.json
----

[source,dockerfile,role="execute",subs=attributes+]
----
cp auth.json /etc/ostree/auth.json
----

(Reminder, the password for `sudo` is `redhat`)
[source,bash,role="execute",subs=attributes+]
----
sudo bootc update
----

Notice that `bootc update` provides information about the layers that have been modified and a progress indicator. The update mechanism also uses container tools to pull the image from the registry to the host for preparation. This means we only pull down the layers that were changed, not the full image if not needed. Later versions of `bootc` will expand this idea of delta updated to further reduce the time and bandwidth used for updates.

The final output should look something like this:
....
layers already present: 67; layers needed: 4 (185.1 MB)
Fetched layers: 176.49 MiB in 28 seconds (6.26 MiB/s)                                   
  Deploying: done (5 seconds)                                                           
Queued for next boot: node.cxdrb.cxdrb.gcp.redhatworkshops.io/httpd
  Version: 9.20250326.0
  Digest: sha256:737be173b45120c062473e9a88d020bc33c32a9069d4c257b74e4f5ab7241e41
Total new layers: 71    Size: 1.2 GB
Removed layers:   3     Size: 185.1 MB
Added layers:     4     Size: 185.1 MB
....

Let's check the current status of the host.
[source,bash,role="execute",subs=attributes+]
----
sudo bootc status
----
....
Current staged image: node.cxdrb.cxdrb.gcp.redhatworkshops.io/httpd <1>
    Image version: 9.20250326.0 (2025-04-04 14:28:06.536999208 UTC)
    Image digest: sha256:737be173b45120c062473e9a88d020bc33c32a9069d4c257b74e4f5ab7241e41
Current booted image: node.cxdrb.cxdrb.gcp.redhatworkshops.io/httpd
    Image version: 9.20250326.0 (2025-04-04 14:11:45.808515934 UTC)
    Image digest: sha256:1e69b8a519eccf248e235960dd5eef3c5c546226c0000c655126e00e11438519
No rollback image present
....
<1> The SHA in the `staged` block should match the Digest from the output of `bootc update`. You will also see the timestamp of the change. Since the base image is the same, no change shows up in the version output.

Updates to bootc hosts are offline in nature, meaning the new image has been readied for deployment, but no other changes have been made to the running system. 

The last step for the change to take is to reboot the virtual machine. Before doing so, please make sure you are logged in to the virtual machine and not the hypervisor, the prompt should look like `[{vm_user}@localhost ~]$`.

[source,bash,role="execute",subs=attributes+]
----
sudo systemctl reboot
----

[#testing]
== Testing the changes

[source,bash,role="execute",subs=attributes+]
----
cat /proc/cmdline
----

[source,bash,role="execute",subs=attributes+]
----
sudo bootc status
----
