= Build a bootc image
In this exercise, you will see how to apply application container build concepts to a bootc image.

[#write]
== Create the Containerfile

[NOTE]
====
The instructions will reflect `nano` commands.

In `nano`, you can save and exit with `Ctrl+x`, followed by the key `y` at the "Save modified buffer?" prompt 
and the `Enter` key at the prompt to keep the filename.

The `vim` editor is also available. Users of `vim` should already know the basics
of opening, saving and exiting the editor. 
====

Add software from RHEL sub
[source,bash,role="execute",subs=attributes+]
----
nano Containerfile
----

[source,dockerfile,role="execute",subs=attributes+]
----
FROM registry.redhat.io/rhel10/rhel-bootc:10.1

RUN dnf -y install pcp-zeroconf \
        rsyslog \
        tmux \
        tuned
----

  
3rd party repos

[source,dockerfile,role="execute",subs=attributes+]
----
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

RUN dnf -y install btop iftop
----

[#build]
== Build the first bootc image

As with application containers, you can build this container with standard tools:

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----
The arguments we pass to `podman` are:

  * `--file Containerfile` -> what Containerfile to use for the build
  * `--tag registry-{guid}.{domain}/base` -> the "tag" or name of the resulting container in the format
     <registry>/<repository>

You will see `podman` process each line of the Containerfile just as it would for an application container. Once complete, the last two lines of the output should read like this:

[source,subs=attributes+]
----
Successfully tagged registry-{guid}.{domain}/httpd
f1bea10eb37acf2e78a9b01c6242110c1901adbaf40dbce479241c6c735c58da
----

You have now built your first complete RHEL image as a bootc image!

