== Image mode good ideas

update timer

[source,dockerfile,role="execute",subs=attributes+]
----
RUN systemctl mask bootc-fetch-apply-updates.timer
----

labels

[source,dockerfile,role="execute",subs=attributes+]
----
# Set up some variables and labels to ID images in our environments
MAINTAINER sysadmins@example.com
# RHEL version inherited from bootc base as redhat.version-id and release
LABEL vendor="Example Corp" 
----

lint all the things
[source,dockerfile,role="execute",subs=attributes+]
----
RUN bootc container lint
----

First, let's set up a directory structure that mimics `/etc` and create the 
files we need inside it. This allows us to add all the configs at once with a single command and in 
a single layer of the image.

NOTE: This is a local directory, relative to the location of the Containerfile, not the system `/etc/`.

[source,bash,role="execute",subs=attributes+]
----
mkdir -p etc/sudoers.d
----
[source,bash,role="execute",subs=attributes+]
----
mkdir -p etc/ostree
----
[source,bash,role="execute",subs=attributes+]
----
mkdir -p usr/lib/bootc/kargs.d
----

[source,bash,role="execute",subs=attributes+]
----
mv 10-wheel etc/sudoers.d
----
[source,bash,role="execute",subs=attributes+]
----
mv console_kargs.conf usr/lib/bootc/kargs.d/05-cloud-kargs.toml
----

Replace the individual file COPY lines with directory ADDs
[source,dockerfile,role="execute",subs=attributes+]
----
ADD etc/ /etc
ADD usr/ /usr
----

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----

[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

Apply our final update
[source,bash,role="execute",subs=attributes+]
----
sudo bootc update --apply
----


OH NO rollback VM:
[source,bash,role="execute",subs=attributes+]
----
sudo bootc upgrade --check
----


[source,bash,role="execute",subs=attributes+]
----
ls /etc/ostree
----


[source,bash,role="execute",subs=attributes+]
----
sudo bootc status
----
....
● Booted image: registry-mjghb.apps.ocpvdev01.rhdp.net/base
        Digest: sha256:10eb5e2ebba0e549deb43315786731ff976d544f6f682c4cf30de0f4c371a059 (amd64)
       Version: 10.1 (2025-11-13T17:17:56Z)

  Rollback image: registry-mjghb.apps.ocpvdev01.rhdp.net/base
          Digest: sha256:d83d9f48a16e98c2d8ca2240f99ce0e2d2ffc5bc948d0434bff1810d2b58e6d5 (amd64)
         Version: 10.1 (2025-11-13T17:30:16Z)
....

[source,bash,role="execute",subs=attributes+]
----
sudo bootc rollback --apply
----


Back to builder to see why:
[source,bash,role="execute",subs=attributes+]
----
ll etc/ostree/
----
....
total 0
....

[source,bash,role="execute",subs=attributes+]
----
ll .
----
[source,bash,role="execute",subs=attributes+]
----
 mv auth.json etc/ostree/
----

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----

[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

VM:
[source,bash,role="execute",subs=attributes+]
----
sudo bootc update --apply
----
[source,bash,role="execute",subs=attributes+]
----
sudo bootc update --check
----
....
No changes in: docker://registry-mjghb.apps.ocpvdev01.rhdp.net/base
....
