---
virtualmachines:
  - name: "builder"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 4
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    packages:
      - podman
      - skopeo
      - virt-install
      - libvirt
      - qemu-kvm
      - libvirt-nss
    terminals:
      - name: wetty_bootc_vm
        command: /root/wait_for_bootc_vm.sh
    services:
      - name: registry-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: registry-http
      
      - name: registry
        ports:
          - port: 5000
            protocol: TCP
            targetPort: 5000
            name: registry
    routes:
      - name: registry-http
        host: registry
        service: registry-http
        targetPort: 80
        tls: false
        path: "/.well-known/"
      
      - name: registry
        host: registry
        service: registry
        targetPort: 5000
        tls: false
