---
virtualmachines:
  - name: "builder"
    image: "rhel-9.5"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    terminals:
      - name: wetty_bootc_vm
        command: /root/wait_for_bootc_vm.sh
    services:
      - name: builder-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: builder-http
    routes:
      - name: builder-http
        host: builder
        service: builder-http
        targetPort: 80
        tls: false
