---
virtualmachines:
  - name: "builder"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 4
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    packages:
      - podman
      - skopeo
      - virt-install
      - libvirt
      - qemu-kvm
      - libvirt-nss
    terminals:
      - name: wetty_bootc_vm
        command: /root/wait_for_bootc_vm.sh
    services:
      - name: builder-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: builder-http
      - name: builder-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: builder-https
    routes:
      - name: builder-http
        host: builder
        service: builder-http
        targetPort: 80
        tls: false
        path: "/.well-known/"
      - name: builder-https
        host: builder
        service: builder-https
        targetPort: 443
        tls: true
